### PR TITLE
Code update and folder restructure

### PR DESCRIPTION
**Pull request by thecre8tor**
Good Day Waleed,
I hope this pull request meet you well,
I admire your work, and I love the way 
you write your code too.

The reason for this pull request is: I encounter
compile and runtime errors when I run this project,
so I decide to fix the bugs.

I worked on the home_master.dart screen,
I refactored lot of code there, most especially
the sidebar navigation, the Appbar and its
screens.

I will appreciate if you can go through the code,
run it to see the changes that as come to the
sidebar and the logic which opens and close it. 

Thanks,
Best Regards.

### CODE REVIEW

**Comment by wal33d006** [comment]
Good day @TheCre8tor 

 I was out of the community stuff due to moving to a new place. I just saw your PR. Can you resolve all the conflicts? I will look into it after the conflicts are resolved.

Thanks for the contribution.

**Comment by thecre8tor** [comment]
Alright, I'm going to resolve the conflicts.

**Review by thecre8tor — COMMENTED** [review]
I have reviewed the code, kindly check.

**Comment by wal33d006** [comment]
The PR still says there are conflicts

**Comment by thecre8tor** [comment]
Done.

**Comment by wal33d006** [comment]
You need to pull the latest master in your branch and resolve the conflicts there (probably inside your IDE). The PR still shows conflicts and you haven't pushed anything to resolve them.

**Comment by TheCre8tor** [comment]
I saw where the problem is coming from, 
In the refactored code, I remove "flutter_bloc" 
and use "provider" only since it's a small project.

This branch is working as expected:
https://github.com/TheCre8tor/novel_covid_19/tree/rf-app_upgrade

Clone this branch and run it. Thanks

**Comment by thecre8tor** [comment]
I'm going to refactor the master branch, 
while maintaining the code as it is.
I will inform you when I am done.

But for now, clone this branch and test it:
https://github.com/TheCre8tor/novel_covid_19/tree/rf-app_upgrade

Let me know your opinion about it. Thanks

**Comment by wal33d006** [comment]
You must have branched out from master so it should ideally show no conflicts

**Comment by TheCre8tor** [comment]
> You must have branched out from master so it should ideally show no conflicts

My mistake.

**Comment by thecre8tor** [comment]
I'm already working on it.

**Pull request closed without merging**
